#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ChallengeMapPoiMarker

#include "Basic.hpp"

#include "ChallengeMapPoiMarker_classes.hpp"
#include "ChallengeMapPoiMarker_parameters.hpp"


namespace SDK
{

// Function ChallengeMapPoiMarker.ChallengeMapPoiMarker_C.ExecuteUbergraph_ChallengeMapPoiMarker
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UChallengeMapPoiMarker_C::ExecuteUbergraph_ChallengeMapPoiMarker(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ChallengeMapPoiMarker_C", "ExecuteUbergraph_ChallengeMapPoiMarker");

	Params::ChallengeMapPoiMarker_C_ExecuteUbergraph_ChallengeMapPoiMarker Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ChallengeMapPoiMarker.ChallengeMapPoiMarker_C.HandleTextChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsRedacted                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UChallengeMapPoiMarker_C::HandleTextChanged(bool bIsRedacted)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ChallengeMapPoiMarker_C", "HandleTextChanged");

	Params::ChallengeMapPoiMarker_C_HandleTextChanged Parms{};

	Parms.bIsRedacted = bIsRedacted;

	UObject::ProcessEvent(Func, &Parms);
}

}

