#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_Athena_Cabbage

#include "Basic.hpp"

#include "GA_Athena_Cabbage_classes.hpp"
#include "GA_Athena_Cabbage_parameters.hpp"


namespace SDK
{

// Function GA_Athena_Cabbage.GA_Athena_Cabbage_C.ExecuteUbergraph_GA_Athena_Cabbage
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Athena_Cabbage_C::ExecuteUbergraph_GA_Athena_Cabbage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_Cabbage_C", "ExecuteUbergraph_GA_Athena_Cabbage");

	Params::GA_Athena_Cabbage_C_ExecuteUbergraph_GA_Athena_Cabbage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Athena_Cabbage.GA_Athena_Cabbage_C.K2_CommitExecute
// (Event, Public, BlueprintEvent)

void UGA_Athena_Cabbage_C::K2_CommitExecute()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_Cabbage_C", "K2_CommitExecute");

	UObject::ProcessEvent(Func, nullptr);
}

}

