#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GCNS_GM_OnDisplayEmoji

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCNS_GM_OnDisplayEmoji.GCNS_GM_OnDisplayEmoji_C
// 0x0000 (0x01B0 - 0x01B0)
class UGCNS_GM_OnDisplayEmoji_C final : public UFortGameplayCueNotify_Burst
{
public:
	void OnBurst(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UParticleSystemComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents, class UCameraShake* BurstCameraShakeInstance, class ADecalActor* BurstDecalInstance) const;
	void HandleParticleSystem(class UParticleSystemComponent* InputPin, const struct FGameplayCueParameters& Parameters) const;
	void HandleAudioSystem(class UAudioComponent* InputPin, const struct FGameplayCueParameters& Parameters) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCNS_GM_OnDisplayEmoji_C">();
	}
	static class UGCNS_GM_OnDisplayEmoji_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCNS_GM_OnDisplayEmoji_C>();
	}
};

}

