#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: SpatialChallengePunchCardEntry

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SpatialChallengePunchCardEntry.SpatialChallengePunchCardEntry_C
// 0x0000 (0x0268 - 0x0268)
class USpatialChallengePunchCardEntry_C final : public USpatialChallengePunchCardEntry
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SpatialChallengePunchCardEntry_C">();
	}
	static class USpatialChallengePunchCardEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USpatialChallengePunchCardEntry_C>();
	}
};

}

