#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: SpatialFactionPerkTier

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SpatialFactionPerkTier.SpatialFactionPerkTier_C
// 0x0018 (0x0270 - 0x0258)
class USpatialFactionPerkTier_C final : public USpatialFactionPerkTier
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0258(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       highlight_Bottom;                                  // 0x0260(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_TierLevel;                                    // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_SpatialFactionPerkTier(int32 EntryPoint);
	void OnFactionSet(bool bIsCurrentFactionEarned, bool bIsRevealed, int32 FactionNumber);
	void OnInitializePerkTier(int32 PerkLevel, bool bIsRevealed, int32 PerkIndex);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SpatialFactionPerkTier_C">();
	}
	static class USpatialFactionPerkTier_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USpatialFactionPerkTier_C>();
	}
};

}

