#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: SpatialStyleChallengeScreen

#include "Basic.hpp"

#include "SpatialStyleChallengeScreen_classes.hpp"
#include "SpatialStyleChallengeScreen_parameters.hpp"


namespace SDK
{

// Function SpatialStyleChallengeScreen.SpatialStyleChallengeScreen_C.ExecuteUbergraph_SpatialStyleChallengeScreen
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USpatialStyleChallengeScreen_C::ExecuteUbergraph_SpatialStyleChallengeScreen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpatialStyleChallengeScreen_C", "ExecuteUbergraph_SpatialStyleChallengeScreen");

	Params::SpatialStyleChallengeScreen_C_ExecuteUbergraph_SpatialStyleChallengeScreen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SpatialStyleChallengeScreen.SpatialStyleChallengeScreen_C.OnShowFirstTimeInfo
// (Event, Protected, BlueprintEvent)

void USpatialStyleChallengeScreen_C::OnShowFirstTimeInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpatialStyleChallengeScreen_C", "OnShowFirstTimeInfo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SpatialStyleChallengeScreen.SpatialStyleChallengeScreen_C.BndEvt__BPS12_AboutModal_K2Node_ComponentBoundEvent_3_OnAboutModalClosedDynamic__DelegateSignature
// (BlueprintEvent)

void USpatialStyleChallengeScreen_C::BndEvt__BPS12_AboutModal_K2Node_ComponentBoundEvent_3_OnAboutModalClosedDynamic__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpatialStyleChallengeScreen_C", "BndEvt__BPS12_AboutModal_K2Node_ComponentBoundEvent_3_OnAboutModalClosedDynamic__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SpatialStyleChallengeScreen.SpatialStyleChallengeScreen_C.BndEvt__Button_About_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButton*                    Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USpatialStyleChallengeScreen_C::BndEvt__Button_About_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature(class UCommonButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpatialStyleChallengeScreen_C", "BndEvt__Button_About_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature");

	Params::SpatialStyleChallengeScreen_C_BndEvt__Button_About_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SpatialStyleChallengeScreen.SpatialStyleChallengeScreen_C.BndEvt__Button_Previous_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButton*                    Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USpatialStyleChallengeScreen_C::BndEvt__Button_Previous_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature(class UCommonButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpatialStyleChallengeScreen_C", "BndEvt__Button_Previous_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature");

	Params::SpatialStyleChallengeScreen_C_BndEvt__Button_Previous_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SpatialStyleChallengeScreen.SpatialStyleChallengeScreen_C.BndEvt__Button_Next_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButton*                    Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USpatialStyleChallengeScreen_C::BndEvt__Button_Next_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature(class UCommonButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpatialStyleChallengeScreen_C", "BndEvt__Button_Next_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature");

	Params::SpatialStyleChallengeScreen_C_BndEvt__Button_Next_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SpatialStyleChallengeScreen.SpatialStyleChallengeScreen_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void USpatialStyleChallengeScreen_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpatialStyleChallengeScreen_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}

}

